version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pi
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backendpi:
    build: .
    container_name: pi-backendpi-1
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: pi
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
      MAIL_USERNAME: mimibhaj@gmail.com
      MAIL_PASSWORD: "fefk ofil layf ciqg"
      JWT_ISSUER_URI: http://backendpi:8081/realms/pi-school
      UPLOAD_DIR: /app/uploads/
      JOBAPP_UPLOAD_DIR: /app/uploads/job
      FACEBOOK_CLIENT_ID: 1160500819178201
      FACEBOOK_CLIENT_SECRET: 42a8fab8ae8e9f847979a38354080a52
      COHERE_TOKEN: uL5ujd2NT0otC7C1sh5QpdjwMr7fo1E6efPipiDK

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8083:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: always

volumes:
  mysql_data:
  nexus-data:
