name: Build and Push Docker Image

on:
  push:
    branches:
      - meriemBH    # Change si ta branche principale s'appelle différemment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: 📦 Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: 🐳 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🛠️ Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pi:latest .

      - name: 🚀 Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pi:latest
