name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./pi

      - name: Build and SonarCloud Scan with Maven
        run: mvn -B verify -DskipTests org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ziedtuihri_PI_BackEnd -Dsonar.organization=ziedtuihri
        working-directory: ./pi
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_SECRET_TOKEN }}

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t meriem01/pi-backend:latest ./pi

      # Push Docker image
      - name: Push Docker image
        run: docker push meriem01/pi-backend:latest

      # Upload JAR artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: pi-backend-jar
          path: ./pi/target/*.jar
