name: CI with SonarCloud & Nexus

on:
  push:
    branches: [ "meriemBH" ]
  pull_request:
    branches: [ "meriemBH" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Cache Sonar
      - uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # Configure Maven settings for Nexus
      - run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Build and test
        run: mvn clean test
        working-directory: ./pi

      - name: SonarCloud scan
        run: mvn verify sonar:sonar \
          -Dsonar.projectKey=ziedtuihri_PI_BackEnd \
          -Dsonar.organization=pidevspringprojects \
          -Dsonar.login=${{ secrets.SONARCLOUD_SECRET_TOKEN }}
        working-directory: ./pi

      - name: Deploy to Nexus
        run: mvn deploy
        working-directory: ./pi
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
