name: Java CI with Maven and Nexus Deploy

on:
  push:
    branches: [ "meriemBH" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./pi

      - name: Deploy JAR to Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }} # ex: https://xxxxxx.ngrok-free.app/repository/maven-releases/
        run: |
          mvn deploy:deploy-file \
            -Durl=$NEXUS_URL \
            -DrepositoryId=nexus \
            -Dfile=./pi/target/pi-0.0.1-SNAPSHOT.jar \
            -DgroupId=tn.esprit \
            -DartifactId=pi \
            -Dversion=0.0.1-SNAPSHOT \
            -Dpackaging=jar \
            -DgeneratePom=true \
            -DretryFailedDeploymentCount=3 \
            -Dusername=$NEXUS_USERNAME \
            -Dpassword=$NEXUS_PASSWORD
